### ISSUE TITLE
Screen goes blank

### ISSUE THREAD

**Issue by SofiaPe** [RecastAI/Recast.AI#101]
Hi, I am trying to modify my bot's skills on the build option, but when I click on the action or trigger buttons the screen goes blank. The same thing has been happening to me for a couple of weeks now 
on different procedures: trainig, looking at the profile, chating with the bot, building, etc, and you have been solving it, but I really need a more permanent sollution so I don't have to stop working on my bot for so long every time it happens.

Here are the older reports:
https://github.com/RecastAI/Recast.AI/issues/90#issue-371225330
https://github.com/RecastAI/Recast.AI/issues/100#issue-375521775

Thanx for the help!

**Comment by janteuni** [comment]
Hello,

I'm sorry for this issues. Can you describe me more the context of this issue.
Maybe you can record your screen when it's happening, so I can understand better. I'm trying to reproduce it and in my bots I'm able to click on triggers or actions.
You can also send me the link of your chatbot, so I can investigate better ;)

Thanks,
Jasmine

**Comment by SofiaPe** [comment]
Hi Jasmine, sorry for the delay in the answer, the bot had been working fine untill today. I can't record the sreen but here is a group of pictures with the step by step of what keeps happening. I don't do anything special, just type a word on my test chat and press enter. Instead of giving me an answer the screen goes blank. It usually happens on different steps of the process, then it works fine and a few days or hours later starts happening again on a different step. 

![1 blan](https://user-images.githubusercontent.com/44376168/48566811-b3f44200-e8c9-11e8-9849-d9e66522aefc.PNG)
![2 blan](https://user-images.githubusercontent.com/44376168/48566827-b9518c80-e8c9-11e8-8404-df641c028337.PNG)
![3 blan](https://user-images.githubusercontent.com/44376168/48566826-b9518c80-e8c9-11e8-9fe5-f882084e47e2.PNG)

**Comment by SofiaPe** [comment]
This problem happens when i have a Quick reply, but only on the test chat, the connect channels work fine. I just read an old post from someone else with the same problem: https://github.com/RecastAI/Recast.AI/issues/40#issue-329075010

**Comment by genshtab** [comment]
Hello there,

same issue happened to my bot. Everything was working perfect last night, but  today  I am getting blank screen when trying to get Quick Reply bttons. Please advice

**Comment by aurelie-lamy** [comment]
The issue is fixed now

**Comment by genshtab** [comment]
Actually I am still getting the same problem. Blank screen when webhook posts to the bot a list of quick reply  buttons.

**Comment by genshtab** [comment]
Now it works fine. Thanks!
