### ISSUE TITLE
Fallback to SAP CEC doesn't work

### ISSUE THREAD

**Issue by sathianarayananh** [RecastAI/Recast.AI#71]
After the issue #65 has been resolved, I can assign a group (queue) now. But still the fallback to CEC doesn’t work. I don’t receive any incoming chat request in CEC.

**Comment by dannyboy2k** [comment]
I'm experiencing the exact same issue.

**Comment by ftriquet** [comment]
Oh I didn't see #71 I close this one

**Comment by ftriquet** [comment]
Hello guys we fixed the issue. Thank you for reporting the bug

**Comment by ftriquet** [comment]
Hello, we are currently facing a last problem, it will be fixed by tomorrow. Sorry again

**Comment by dannyboy2k** [comment]
I just tested it and i still don't recieve an incoming chat request in CEC. In Debug mode it says the fallback is triggered:

Fallback triggered

{
  "type": "fallback",
  "value": {
    "channel_id": "cfdc5844-c48e-4353-8d7d-6b13e8639e9a",
    "redirection_group": ""
  }
}
